--- 

- name: Boostrap system
  hosts: all
  user: aiden
  become: true
  vars:
    - mounts:
        - { path: /mnt/nfs/sandboxdata, src: nas.homelan.win:/nfs-minilab-sandbox-data, fstype: nfs, opts: "vers=3,sec=sys" }
  roles:
    - { role: bootstrap, tags: bootstrap }

- name: Provision docker
  hosts: all
  user: aiden
  become: true
  roles:
    - { role: docker_host, tags: docker_host }


- name: Provision postgres
  hosts: all
  user: aiden
  become: true
  vars:
    - postgresql__postgres_data_target: /mnt/nfs/sandboxdata/postgresdata
  roles:
    - { role: postgres, tags: postgres }

- name: Provision Traefik
  become: true
  hosts: all
  vars:
    docker_traefik__host_uri: s-noc.homelan.win
    docker_traefik__acme_email: aiden.webb@gmail.com
    docker_traefik__default_env:
      CF_API_EMAIL: "{{ lookup('ansible.builtin.env','CLOUDFLARE_API_EMAIL') }}"
      CF_DNS_API_TOKEN: "{{ lookup('ansible.builtin.env','CLOUDFLARE_DNS_API_TOKEN') }}"
  roles:
    - { role: docker_traefik, tags: docker_traefik }

- name: Provision Admin tools
  become: true
  hosts: all
  roles:
    - { role: admin_tools, tags: admin_tools }

# - name: Provision Elk Stack
#   become: true
#   hosts: all
#   roles:
#     - { role: elk_stack, tags: elk_stack }

- name: Provision Graylog Stack
  become: true
  hosts: all
  vars: 
    graylog_stack__graylog_password_secret: mDkttEu4VAtmikOBOkQ4b74Nc4DbJStKAMhATTOolaB5s3Tqkk5Fx73Pr4iVOr6YDrAFA0Lo9sbRPJRMiMUwOLodDv6GMIKn
  roles: 
    - { role: graylog_stack, tags: graylog_stack }