---
- name: Create /opt/elk_stack directory
  ansible.builtin.file:
    path: /opt/elk_stack
    state: directory
    mode: 0750

- name: Clone Docker Elk repo
  git:
    repo: https://github.com/deviantony/docker-elk.git
    dest: /opt/elk_stack

- name: Deploy compose stack
  docker_compose:
    project_src: /opt/elk_stack
    files:
      - docker-compose.yml
