---
- name: Download k3s binary
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s__k3s_version }}/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s__k3s_version }}/sha256sum-amd64.txt
    dest: "{{ role_path }}/files/bin/k3s"
    mode: "0755"
  delegate_to: localhost
  run_once: true
  register: k3s__k3s_binary

- name: Copy k3s binary to nodes
  ansible.builtin.copy:
    src: bin/k3s
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"

- name: Ensure the config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/rancher/k3s
    - /etc/rancher/node

- name: Check if k3s token file exists on first node - will use this token for all nodes
  run_once: true
  ansible.builtin.stat:
    path: "{{ k3s__k3s_token_file }}"
  register: k3s__k3s_token_file_stat

- name: Generate k3s token on first node if missing
  run_once: true
  when: not k3s__k3s_token_file_stat.stat.exists
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits') }}"
    dest: "{{ k3s__k3s_token_file }}"
    owner: root
    group: root
    mode: "0600"

- name: Get k3s token from first node
  run_once: true
  ansible.builtin.slurp:
    src: "{{ k3s__k3s_token_file }}"
  register: k3s__k3s_token_file_from_first_node

- name: Copy first node's k3s token to all nodes
  ansible.builtin.copy:
    content: "{{ k3s__k3s_token_file_from_first_node['content'] | b64decode }}"
    dest: "{{ k3s__k3s_token_file }}"
    owner: root
    group: root
    mode: "0600"

- name: Copy k3s config template to nodes
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - src: config.yaml.j2
      dest: /etc/rancher/k3s/config.yaml

- name: Copy k3s systemd service template to nodes
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: "0644"
  notify: 
  - Restart k3s

- name: Enable and start k3s service
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true
  register: k3s__k3s_service_result
  until: k3s__k3s_service_result is succeeded
  retries: 5

- name: Slurp the Kubernetes Config File from first node
  run_once: true
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s__k3s_config_file

- name: Write Kubernetes Config file to local disk with correct cluster address
  run_once: true
  ansible.builtin.copy:
    content: "{{ k3s__k3s_config_file['content'] | b64decode | replace('127.0.0.1', hostvars[groups['masters'][0]].ansible_host) }}"
    dest: "{{ k3s__k3s_config_file_local_path }}"
    mode: "0600"
  delegate_to: localhost
