apiVersion: v2
name: argo
description: A Helm chart for Argo
# https://github.com/argoproj/argo-helm
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 5.27.5
    repository: https://argoproj.github.io/argo-helm