---
- name: Create /opt/adminer directory
  ansible.builtin.file:
    path: /opt/adminer
    state: directory
    mode: 0750

- name: Copy compose file
  copy:
    src: files/adminer/{{ item }}
    dest: /opt/adminer/{{ item }}
    mode: 0640
  with_items:
    - docker-compose.yml

- name: Copy env template
  template:
    src: templates/adminer/.env.j2
    dest: /opt/adminer/.env
    mode: 0640

- name: Deploy compose stack
  docker_compose:
    project_src: /opt/adminer
    files:
      - docker-compose.yml
