--- 

- name: Boostrap system
  hosts: all
  user: root
  become: true
  vars:
    - mounts:
        - { path: /mnt/nfs/reverseproxydata, src: nas.homelan.win:/nas.homelan.win/nfs-minilab-reverseproxydata, fstype: nfs, opts: "vers=4,minorversion=1,sec=sys" }
  roles:
    - { role: bootstrap, tags: bootstrap }

- name: Provision docker on hosts
  hosts: all
  user: root
  become: true
  roles:
    - { role: docker_host, tags: docker_host }

# - name: Deploy Nginx Proxy Manager
#   hosts: all
#   user: root
#   become: true
#   roles:
#     - { role: nginx_proxy_manager_node, tags: nginx_proxy_manager_node }