apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: "{{ gitops__k8s_namespace }}"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: apps
    repoURL: https://github.com/Aidenwebb/MiniLab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
