baremetal:
  children:
    masters:
      hosts:
        baremetal0:
          {
            ansible_host: 192.168.1.237,
            mac: 10:e7:c6:00:70:37,
            disk: sda,
            network_interface: eno1,
          }
