---
- name: Configure interfaces
  template:
    src: "{{ proxmox__network_interfaces_template }}"
    dest: "/root/network_interface"
    owner: "root"
    group: "root"
    mode: "0644"
  when: >
    proxmox__network_interfaces_config is defined and
    proxmox__network_interfaces_template is not none
