---
- name: Download boot image
  ansible.builtin.get_url:
    url: "{{ boot_image_iso_url }}"
    dest: "{{ role_path }}/files/data/iso/{{ boot_image_iso_url | basename }}"
    checksum: "{{ boot_image_iso_checksum }}"
    mode: 0644
  register: boot_iso

- name: Extract boot image
  ansible.builtin.command:
    cmd: "xorriso -osirrox on -indev {{ boot_iso.dest }} -extract / {{ role_path }}/files/data/os"
    creates: "{{ role_path }}/files/data/os/.treeinfo"

- name: Generate DNSMASQ config
  ansible.builtin.template:
    src: "dnsmasq.conf.j2"
    dest: "{{ role_path }}/files/data/pxe-config/dnsmasq.conf"
    mode: 0644

- name: Generate GRUB config
  ansible.builtin.template:
    src: "grub.cfg.j2"
    dest: "{{ role_path }}/files/data/pxe-config/grub.cfg"
    mode: 0644
