---
- import_tasks: prepare_bootimage.yml

- name: Generate DNSMASQ config
  ansible.builtin.template:
    src: "dnsmasq.conf.j2"
    dest: "{{ role_path }}/files/data/pxe-config/dnsmasq.conf"
    mode: 0644

- name: Generate GRUB config
  ansible.builtin.template:
    src: "grub.cfg.j2"
    dest: "{{ role_path }}/files/data/pxe-config/grub.cfg"
    mode: 0644

- name: Generate kickstart init config for each machine
  ansible.builtin.template:
    src: kickstart.ks.j2
    dest: "{{ role_path }}/files/data/init-config/{{ hostvars[item]['mac'] }}.ks"
    mode: 0644
  loop: "{{ groups['baremetal'] }}"
# - name: Start PXE server with docker
#   community.docker.docker_compose:
#     project_src: "{{ role_path }}/files"
#     state: present
#     build: true
