---
- name: Download boot image
  ansible.builtin.get_url:
    url: "{{ boot_image_iso_url }}"
    dest: "{{ role_path }}/files/data/iso/{{ boot_image_iso_dest_filename }}"
    checksum: "{{ boot_image_iso_checksum }}"
    mode: 0644
  register: boot_iso

# Prepare PXE

- name: Extract kernel and initrd
  community.general.iso_extract:
    image: "{{ boot_iso.dest }}"
    dest: "{{ role_path }}/files/data/pxeboot/"
    files:
      - "boot/linux26"
      - "boot/initrd.img"

- name: Rename uncompressed initrd
  ansible.builtin.command:
    cmd: "mv {{ role_path }}/files/data/pxeboot/initrd.img {{ role_path }}/files/data/pxeboot/initrd.tmp.img"
    creates: "{{ role_path }}/files/data/pxeboot/initrd.tmp.img"

- name: Decompress initrd
  ansible.builtin.command:
    cmd: "zstd -d {{ role_path }}/files/data/pxeboot/initrd.tmp.img -o {{ role_path }}/files/data/pxeboot/initrd.img"
    creates: "{{ role_path }}/files/data/pxeboot/initrd.img"

- name: Remove compressed initrd.img
  ansible.builtin.file:
    path: "{{ role_path }}/files/data/pxeboot/initrd.tmp.img"
    state: absent

- name: Add proxmox iso to initrd.img
  ansible.builtin.command:
    cmd: "echo {{ boot_iso.dest }} | cpio -L -H newc -o >> {{ role_path }}/files/data/pxeboot/initrd"
#     creates: "{{ role_path }}/files/data/pxeboot/initrd.img"

