---
- name: Create Proxmox cluster
  hosts: baremetal_pve
  become: true
  become_user: root
  roles:
    - proxmox
  vars:
    - proxmox__vlans: [ 4, 5, 6, 8, 9, 10, 16, 24, 40 ]
      proxmox__network_interfaces_config:
        - name: eno1
          configure: true
          enable: true
          comment: "Physical Interface"
          method: manual
          parameters:
            - param: ovs_type
              value: OVSPort
            - param: ovs_bridge
              value: "{{ proxmox__ovs_bridges_config.0.name }}"
      proxmox__ovs_bridges_config:
        - name: vmbr1
          configure: true
          enable: true
          comment: "OVS Bridge"
          method: manual
          nic: eno1
          ports:
            - eno1
            - vlan0004
            - vlan0005
            - vlan0006
            - vlan0008
            - vlan0009
            - vlan0010
            - vlan0016
            - vlan0024
            - vlan0040
      proxmox__ovs_intports_config:
        - name: vlan0004
          configure: true
          enable: true
          comment: "Management Access Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 4
        - name: vlan0005
          configure: true
          enable: true
          comment: "OOB Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 5
        - name: vlan0006
          configure: true
          enable: true
          comment: "Storage Devices Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 6
        - name: vlan0008
          configure: true
          enable: true
          comment: "Gateway Cluster Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 8
        - name: vlan0009
          configure: true
          enable: true
          comment: "PVE Cluster Network"
          method: static
          address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/24"
          gateway: 172.31.9.1
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 9
        - name: vlan0010
          configure: true
          enable: true
          comment: "K8s Cluster Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 10
        - name: vlan0016
          configure: true
          enable: true
          comment: "Management Apps (No Internet) Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 16
        - name: vlan0024
          configure: true
          enable: true
          comment: "Management Apps (With Internet) Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 24
        - name: vlan0040
          configure: true
          enable: true
          comment: "Local Apps (With Internet) Network"
          method: manual
          bridge: "{{ proxmox__ovs_bridges_config.0.name }}"
          tag: 40